volumes:
    caddy_data: {}
    static: {}
    compiled: {}
services:
    builder:
        build: &build
            dockerfile: ./infrastructure/production/Dockerfile
            target: builder
            context: ../..
        volumes: &volumes
            - /opt/lgweb/db/:/db/
            - /opt/lgweb/reports/:/reports/
            - static:/static/
            - compiled:/compiled/
    server:
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
            - '443:443/udp'
        build:
            <<: *build
            target: server
        env_file:
            - .env.server
        environment:
            - MAIN_URL=main:8000
        volumes:
            - static:/static/
            - compiled:/compiled/
            - caddy_data:/data/
    main:
        restart: unless-stopped
        depends_on:
            builder:
                condition: service_completed_successfully
        env_file:
            - .env
        environment:
            - FORCE_HTTPS=1
        build:
            <<: *build
            target: main
        volumes: *volumes
    cron:
        restart: unless-stopped
        depends_on:
            builder:
                condition: service_completed_successfully
        env_file:
            - .env
        build:
            <<: *build
            target: cron
        volumes: *volumes
