- name: Update web servers
  vars:
    user: admin
  hosts: all
  remote_user: '{{ user }}'
  become: yes

  tasks:
  - name: Ensure all default packages are upgraded
    apt:
      upgrade: dist
      autoremove: yes
      update_cache: yes

  - name: Ensure all required packages are installed
    apt:
      name:
        - nginx
        - ca-certificates
        - curl
        - gnupg
        - snapd
        - sqlite3
      state: present
      autoremove: yes

  - name: Ensure docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Ensure docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
      state: present

  - name: Ensure docker is installed
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      update_cache: yes
      state: present

  - name: Ensure current user is in docker group
    user:
      name: '{{ user }}'
      groups: docker
      append: yes

  - name: Ensure docker deamon is running
    service:
      name: docker
      state: started
    become: true

  - name: Ensure certbot is installed
    community.general.snap:
      name:
        - certbot
      classic: yes
