version: '3.3'
volumes:
    virtualenv: {}
    static: {}
    uploads: {}
    db: {}
    cache: {}
    nodemodules: {}
services:
    main:
        ports:
            - '8000:8000'
        container_name: lgweb-dev
        image: lgweb-dev
        build:
            dockerfile: ./infrastructure/development/Dockerfile
            context: ../..
        env_file:
            - .env
        environment:
            - MODE=development
            - ALLOWED_HOSTS=*
            - STATIC_ROOT=/static
            - MEDIA_ROOT=/uploads
            - LOCALE_PATH=/locales
            - CACHE_DIR=/cache
            - DB_ROOT=/db/db.sqlite3
            - CONTACT_DB_ROOT=/db/contact.sqlite3
            - ANALYTICS_DB_ROOT=/db/analytics.sqlite3
        volumes:
            - ../../:/lgweb/
            - virtualenv:/venv/
            - static:/static/
            - uploads:/uploads/
            - db:/db/
            - cache:/cache/
            - nodemodules:/lgweb/node_modules/
        entrypoint:
            - /bin/sh
            - -c
            - >-
                npm ci --omit=dev &&
                python -m venv /venv &&
                source /venv/bin/activate &&
                pip install wheel &&
                pip install -r requirements.txt &&
                cp -R ./locales /locales &&
                python manage.py migrate &&
                python manage.py migrate --database contact &&
                python manage.py migrate --database analytics &&
                python manage.py seed &&
                python manage.py compilemessages &&
                python manage.py runserver 0.0.0.0:8000
