version: '3.3'
volumes:
    virtualenv: {}
    compiled: {}
    db: {}
    cache: {}
    nodemodules: {}
    caddy_data: {}
services:
    builder: &base
        image: lgweb-dev
        build:
            dockerfile: ./infrastructure/development/Dockerfile
            context: ../..
        env_file:
            - .env
        environment:
            - MODE=development
            - ALLOWED_HOSTS=*
            - STATIC_ROOT=/static
            - COMPILED_ROOT=/compiled
            - LOCALE_PATH=/locales
            - CACHE_DIR=/cache
            - DB_ROOT=/db/db.sqlite3
            - CONTACT_DB_ROOT=/db/contact.sqlite3
            - ANALYTICS_DB_ROOT=/db/analytics.sqlite3
        volumes:
            - ../../:/lgweb/
            - virtualenv:/venv/
            - compiled:/compiled/
            - db:/db/
            - cache:/cache/
            - nodemodules:/lgweb/node_modules/
        entrypoint: npm ci --omit=dev
    server:
        ports:
            - '8000:8000'
            - '8001:8001'
        image: caddy:2-alpine
        environment:
            - MAIN_URL=main:8000
            - WEB_DOMAIN=:8001
            - WEB_HOST=:8000
            - WEB_URL=http://localhost:8000
            - CACHE_CONTROL=max-age=60
        volumes:
            - ../../configs/Caddyfile:/etc/caddy/Caddyfile
            - ../../public:/public
            - compiled:/compiled/
            - caddy_data:/data/
    main:
        <<: *base
        entrypoint:
            - /bin/sh
            - -c
            - >-
                python -m venv /venv &&
                source /venv/bin/activate &&
                pip install wheel &&
                pip install -r requirements.txt &&
                cp -R ./locales /locales &&
                python manage.py migrate &&
                python manage.py migrate --database contact &&
                python manage.py migrate --database analytics &&
                python manage.py compilemessages &&
                python manage.py runserver 0.0.0.0:8000
    css-site:
        <<: *base
        depends_on: &depends_on
            builder:
                condition: service_completed_successfully
        entrypoint:
            - /bin/sh
            - -c
            - >-
                npx sass -s expanded --watch --poll app/styles/index.scss $$COMPILED_ROOT/index.css
    css-richtext:
        <<: *base
        depends_on: *depends_on
        entrypoint:
            - /bin/sh
            - -c
            - >-
                npx sass -s expanded --watch --poll app/styles/richtext.scss $$COMPILED_ROOT/richtext.css
    css-noscript:
        <<: *base
        depends_on: *depends_on
        entrypoint:
            - /bin/sh
            - -c
            - >-
                npx sass -s expanded --watch --poll app/styles/noscript.scss $$COMPILED_ROOT/noscript.css
    css-error:
        <<: *base
        depends_on: *depends_on
        entrypoint:
            - /bin/sh
            - -c
            - >-
                npx sass -s expanded --watch --poll app/styles/error.scss $$COMPILED_ROOT/error.css
    js-site:
        <<: *base
        depends_on: *depends_on
        entrypoint:
            - /bin/sh
            - -c
            - >-
                npx rollup --config rollup.config.mjs --watch --input app/scripts/index.ts --file $$COMPILED_ROOT/index.js
    js-worker:
        <<: *base
        depends_on: *depends_on
        entrypoint:
            - /bin/sh
            - -c
            - >-
                npx rollup --config rollup.config.mjs --watch --input app/scripts/service.worker.ts --file $$COMPILED_ROOT/sw.js
