version: '3.3'
volumes:
    virtualenv: {}
    static: {}
    uploads: {}
    db: {}
    cache: {}
    nodemodules: {}
services:
    builder: &base
        image: lgweb-dev
        build:
            dockerfile: ./infrastructure/development/Dockerfile
            context: ../..
        env_file:
            - .env
        environment:
            - MODE=development
            - ALLOWED_HOSTS=*
            - STATIC_ROOT=/static
            - MEDIA_ROOT=/uploads
            - LOCALE_PATH=/locales
            - CACHE_DIR=/cache
            - DB_ROOT=/db/db.sqlite3
            - CONTACT_DB_ROOT=/db/contact.sqlite3
            - ANALYTICS_DB_ROOT=/db/analytics.sqlite3
        volumes:
            - ../../:/lgweb/
            - virtualenv:/venv/
            - static:/static/
            - uploads:/uploads/
            - db:/db/
            - cache:/cache/
            - nodemodules:/lgweb/node_modules/
        entrypoint: npm ci --omit=dev
    main:
        <<: *base
        ports:
            - '8000:8000'
        entrypoint:
            - /bin/sh
            - -c
            - >-
                python -m venv /venv &&
                source /venv/bin/activate &&
                pip install wheel &&
                pip install -r requirements.txt &&
                cp -R ./locales /locales &&
                python manage.py migrate &&
                python manage.py migrate --database contact &&
                python manage.py migrate --database analytics &&
                python manage.py seed &&
                python manage.py compilemessages &&
                python manage.py runserver 0.0.0.0:8000
    css-site:
        <<: *base
        depends_on: &depends_on
            builder:
                condition: service_completed_successfully
        entrypoint:
            - /bin/sh
            - -c
            - >-
                npx sass -s expanded --watch --poll app/styles/index.scss $$STATIC_ROOT/compiled/index.css
    css-richtext:
        <<: *base
        depends_on: *depends_on
        entrypoint:
            - /bin/sh
            - -c
            - >-
                npx sass -s expanded --watch --poll app/styles/richtext.scss $$STATIC_ROOT/compiled/richtext.css
    css-noscript:
        <<: *base
        depends_on: *depends_on
        entrypoint:
            - /bin/sh
            - -c
            - >-
                npx sass -s expanded --watch --poll app/styles/noscript.scss $$STATIC_ROOT/compiled/noscript.css
    js-site:
        <<: *base
        depends_on: *depends_on
        entrypoint:
            - /bin/sh
            - -c
            - >-
                npx rollup --config rollup.config.mjs --watch --input app/scripts/index.ts --file $$STATIC_ROOT/compiled/index.js
    js-worker:
        <<: *base
        depends_on: *depends_on
        entrypoint:
            - /bin/sh
            - -c
            - >-
                npx rollup --config rollup.config.mjs --watch --input app/scripts/service.worker.ts --file $$STATIC_ROOT/compiled/sw.js
