version: '3.3'
volumes:
    caddy_data: {}
    db: {}
    uploads: {}
    static: {}
    compiled: {}
    reports: {}
services:
    builder:
        build: &build
            dockerfile: ./infrastructure/production/Dockerfile
            target: builder
            context: ../..
        volumes: &volumes
            - db:/db/
            - uploads:/uploads/
            - static:/static/
            - compiled:/compiled/
            - reports:/reports/
    server:
        ports:
            - '8000:8000'
            - '8001:8001'
        build:
            <<: *build
            target: server
        environment:
            - MAIN_URL=main:8000
            - WEB_DOMAIN=:8001
            - WEB_HOST=:8000
            - WEB_URL=http://localhost:8000
        volumes:
            - uploads:/uploads/
            - static:/static/
            - compiled:/compiled/
            - caddy_data:/data/
    main:
        depends_on:
            builder:
                condition: service_completed_successfully
        env_file:
            - .env
        environment:
            - ALLOWED_HOSTS=*
        build:
            <<: *build
            target: main
        volumes: *volumes

